from .generic_exceptions import handle_internal_error